# -*- coding: utf-8 -*-
"""ANN_LR3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16iA5-zNE-XCbmvqcc7X0otGE7W062jDb

# Подготовка базы
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, BatchNormalization
from tensorflow.keras.layers import Dense, Activation, Input
from tensorflow.keras import utils
from tensorflow.keras.optimizers import Adam
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
# %matplotlib inline

df = pd.read_csv("sonar.csv", header=None)
print(df.shape)
df.head()

dataset = df.replace('R', 1.).replace('M', 0.).astype(float).to_numpy()

x_data = dataset[:, :60]
y_data = dataset[:, 60]

print('Размерность набора параметров объектов', x_data.shape)
print('Размерность набора меток класса', y_data.shape)
print()
print('Содержание y_data:', y_data)

#функция случайно делит датасет на обучающую и тестовые части
x_train, x_test, y_train, y_test = train_test_split(
    x_data,        # параметры
    y_data,        # метки классов
    test_size=0.2, # процент в тестовую
    shuffle=True,  # перемешивание
    random_state=3 # воспроизводимость
)

print('Обучающая выборка параметров', x_train.shape)
print('Обучающая выборка меток классов', y_train.shape)
print()
print('Тестовая выборка параметров', x_test.shape)
print('Тестовая выборка меток классов', y_test.shape)

"""# Обучение нейросети"""

def create_model():
  # Создание модели
    model = Sequential()
    # Добавление слоев
    model.add(Input(shape=(x_train.shape[1],)))   # слой 0: вход
    model.add(Dense(60, activation='relu'))       # слой 1
    model.add(Dense(30, activation='relu'))       # слой 2
    model.add(Dense(4, activation='sigmoid'))     # слой 3: выход
# Компиляция и возврат модели
    model.compile(loss='binary_crossentropy',
                  optimizer=Adam(learning_rate=0.001),
                  metrics=['accuracy'])
    return model

model = create_model()
model.summary()

print("y_train.shape:", y_train.shape)          # ожидается (1600, 4)
print("model.output_shape:", model.output_shape) # ожидается (None, 4)
print("Совпадает:", y_train.shape[1] == model.output_shape[1])

"""# Оценка качества обучения

Создание  валидационной выборки.
"""

# Обучение нейронной сети
history = model.fit(x_train,               # Обучающая выборка параметров
          y_train,               # Обучающая выборка меток класса
          batch_size=8,          # Размер батча (пакета)
          epochs=100,            # Количество эпох обучения
          validation_split=0.2,  # Доля проверочной выборки
          verbose=1)             # Отображение хода обучения

""" Посмотреть точность на проверочной выборке"""

scores = model.evaluate(x_test,
                        y_test,
                        verbose=1
                        )

"""# Визуализация качества обучения"""

# Визуализация точности на обучающей выборке
plt.plot(history.history['accuracy'],
         label='Доля верных ответов на обучающем наборе')

# Визуализация точности на проверочной выборке
plt.plot(history.history['val_accuracy'],
         label='Доля верных ответов на проверочном наборе')

# Отрисовка подписей осей
plt.xlabel('Эпоха обучения')
plt.ylabel('Доля верных ответов')

# Отрисовка легенды
plt.legend()

# Вывод графика
plt.show()

#График ошибки
plt.plot(history.history['loss'],
         label='Ошибка на обучающем наборе')
plt.plot(history.history['val_loss'],
         label='Ошибка на проверочном наборе')

plt.xlabel('Эпоха обучения')
plt.ylabel('Ошибка')

plt.legend()

plt.show()

"""# Слой Dropout"""

# Создание последовательной модели
model = Sequential()
model.add(Input(shape=(x_train.shape[1],)))
model.add(Dense(60, activation='relu'))
model.add(Dropout(0.3))
model.add(Dense(30, activation='relu'))
model.add(Dropout(0.3))
model.add(Dense(4, activation='sigmoid'))

# Компиляция модели
model.compile(loss='binary_crossentropy', optimizer=Adam(learning_rate=0.001), metrics=['accuracy'])

# Обучение сети
history = model.fit(x_train,
                    y_train,
                    batch_size=8,
                    epochs=200,
                    validation_split=0.2,
                    verbose=1)

# Краткая сводка архитектуры модели
model.summary()
# Отрисовка графика точности на обучающей выборке
# label - имя графика в легенде
plt.plot(history.history['accuracy'],
         label='Доля верных ответов на обучающем наборе')
plt.plot(history.history['val_accuracy'],
         label='Доля верных ответов на проверочном наборе')
plt.xlabel('Эпоха обучения')
plt.ylabel('Доля верных ответов')
plt.legend()
plt.show()
# Вывод графика ошибки
plt.plot(history.history['loss'],
         label='Ошибка на обучающем наборе')
plt.plot(history.history['val_loss'],
         label='Ошибка на проверочном наборе')
plt.xlabel('Эпоха обучения')
plt.ylabel('Ошибка')
plt.legend()
plt.show()

# Вычисление результата (предсказания) сети на тестовом наборе
scores = model.evaluate(x_test, y_test, verbose=1)

print(scores)
print('Доля верных ответов на тестовых данных, в процентах: {:7.4%}'.format(scores[1]))

"""Слой BatchNormalization
Изменим архитектуру сети, добавим слой BatchNormalization

"""

model = Sequential()

model.add(BatchNormalization(input_shape=(x_train.shape[1], )))
model.add(Dense(60, activation='relu'))
model.add(BatchNormalization())
model.add(Dense(30, activation='relu'))
model.add(Dense(4, activation='sigmoid'))

model.compile(loss='binary_crossentropy',
              optimizer=Adam(learning_rate=0.001),
              metrics=['accuracy'])

history = model.fit(x_train,
                    y_train,
                    batch_size=200,
                    epochs=100,
                    validation_split=0.2,
                    verbose=1)

plt.plot(history.history['accuracy'],
         label='Доля верных ответов на обучающем наборе')
plt.plot(history.history['val_accuracy'],
         label='Доля верных ответов на проверочном наборе')
plt.xlabel('Эпоха обучения')
plt.ylabel('Доля верных ответов')
plt.legend()
plt.show()

plt.plot(history.history['loss'],
         label='Ошибка на обучающем наборе')
plt.plot(history.history['val_loss'],
         label='Ошибка на проверочном наборе')
plt.xlabel('Эпоха обучения')
plt.ylabel('Ошибка')
plt.legend()
plt.show()

"""# Практическое задание 1"""

model = Sequential()
#нормализует входные данные перед подачей в сеть.
model.add(BatchNormalization(input_shape=(x_train.shape[1],)))


model.add(Dense(60, activation='relu')) #1 слой
model.add(BatchNormalization()) #нормализует выходы 1-го слоя
model.add(Dropout(0.3)) #защита от переобучения (отключения 30 нейронов на каждой эпохи)

model.add(Dense(30, activation='relu'))
model.add(BatchNormalization())
model.add(Dropout(0.3))

model.add(Dense(4, activation='softmax'))

#для 4 классов categorical_crossentropy
model.compile(loss='categorical_crossentropy',
              optimizer=Adam(learning_rate=0.001),
              metrics=['accuracy'])

#запуск обучения
history = model.fit(x_train,              #Признаки для обучения
                    y_train,              #Метки (one-hot) для обучения
                    batch_size=8,         #Сколько объектов обрабатывается за один шаг
                    epochs=200,           #Сколько раз пройти по всему датасету
                    validation_split=0.2, #Keras отрежет 20% от x_train для валидации
                    verbose=1)            #Показывать прогресс-бар

model.summary()

# Графики
plt.plot(history.history['accuracy'], label='Доля верных ответов на обучающем наборе')
plt.plot(history.history['val_accuracy'], label='Доля верных ответов на проверочном наборе')
plt.xlabel('Эпоха обучения')
plt.ylabel('Доля верных ответов')
plt.legend()
plt.show()

plt.plot(history.history['loss'], label='Ошибка на обучающем наборе')
plt.plot(history.history['val_loss'], label='Ошибка на проверочном наборе')
plt.xlabel('Эпоха обучения')
plt.ylabel('Ошибка')
plt.legend()
plt.show()

scores = model.evaluate(x_test, y_test, verbose=1)
print('Доля верных ответов на тестовых данных: {:7.4%}'.format(scores[1]))

"""# Практическое задание"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.utils import to_categorical
from sklearn.model_selection import train_test_split   # ← добавлен импорт

# --- Загрузка ---
df = pd.read_csv("train.csv", sep=';')   # разделитель ';'
print("Размер:", df.shape)

# --- Признаки и метки ---
x_data = df.drop('price_range', axis=1).to_numpy()  # все колонки кроме метки — признаки
y_data = df['price_range'].to_numpy()                # колонка price_range — метки (0..3)

# --- Масштабирование ---
scaler = StandardScaler()                  # приводит признаки к μ=0, σ=1
x_data = scaler.fit_transform(x_data)      # обучаем scaler на данных и применяем

# --- One-hot encoding для 4 классов ---
y_data = to_categorical(y_data, num_classes=4)

# --- Разделение ---
x_train, x_test, y_train, y_test = train_test_split(
    x_data,              # признаки
    y_data,              # метки (one-hot)
    test_size=0.2,       # 20% в тестовую выборку
    random_state=42,     # воспроизводимость
    stratify=y_data      # сохранить пропорции 4 классов
)

print("x_train:", x_train.shape, "y_train:", y_train.shape)  # (1600, 20) (1600, 4)
print("x_test :", x_test.shape,  "y_test :", y_test.shape)   # (400, 20)  (400, 4)

"""Архитектуры

"""

def model_v1():
    """Простая модель: 2 скрытых слоя без регуляризации."""
    model = Sequential([
        Input(shape=(x_train.shape[1],)),   # форма входа: 20 признаков
        Dense(64, activation='relu'),        # 1-й скрытый слой, 64 нейрона
        Dense(32, activation='relu'),        # 2-й скрытый слой, 32 нейрона
        Dense(4, activation='softmax')       # выход: 4 класса (0..3)
    ])
    model.compile(loss='categorical_crossentropy',   # для one-hot меток
                  optimizer=Adam(learning_rate=0.001),# шаг обучения 0.001
                  metrics=['accuracy'])               # следим за точностью
    return model

def model_v2():
    """Модель с BatchNormalization + Dropout — против переобучения."""
    model = Sequential([
        Input(shape=(x_train.shape[1],)),    # форма входа: 20 признаков

        Dense(128, activation='relu'),       # 1-й скрытый слой, 128 нейронов
        BatchNormalization(),                # нормализует выходы 1-го слоя
        Dropout(0.4),                        # выключает 40% нейронов → защита от переобучения

        Dense(64, activation='relu'),        # 2-й скрытый слой, 64 нейрона
        BatchNormalization(),                # нормализует выходы 2-го слоя
        Dropout(0.3),                        # выключает 30% нейронов

        Dense(32, activation='relu'),        # 3-й скрытый слой, 32 нейрона
        Dense(4, activation='softmax')       # выход: 4 класса
    ])
    model.compile(loss='categorical_crossentropy',   # для one-hot меток
                  optimizer=Adam(learning_rate=0.0005),# шаг меньше — стабильнее
                  metrics=['accuracy'])
    return model

# --- Обучение и сравнение ---
plt.figure(figsize=(10, 5))
results = {}

for name, create_fn in [('V1', model_v1), ('V2', model_v2)]:
    print(f'--- Модель {name} ---')

    model = create_fn()              # создаём НОВУЮ модель для каждой архитектуры
    history = model.fit(x_train, y_train,       # признаки и метки для обучения
                        batch_size=32,          # 32 объекта за один шаг
                        epochs=100,             # 100 проходов по датасету
                        validation_split=0.2,   # 20% train уйдёт в валидацию
                        verbose=0)              # без прогресс-бара

    # Кривая точности на валидации для текущей модели
    plt.plot(history.history['val_accuracy'], label=f'{name} val')

    # Оценка на отложенной тестовой выборке
    scores = model.evaluate(x_test, y_test, verbose=0)  # [loss, accuracy]
    results[name] = scores[1]        # запоминаем accuracy
    print(f'Точность на тесте ({name}): {scores[1]:.4f}')

    model.summary()                  # архитектура модели

# Оформление графика
plt.xlabel('Эпоха обучения')         # подпись оси X
plt.ylabel('Доля верных ответов')    # подпись оси Y
plt.legend()                         # легенда с именами V1/V2
plt.title('Сравнение архитектур (Mobile Price)')
plt.show()

# --- Итог ---
print("\nИтог:")
for k, v in results.items():
    print(f'  {k}: {v:.4%}')         # вывод в процентах